### ISSUE TITLE
GENERAl: Change sign in feature to UGent Login with CAS, remove signup

### ISSUE THREAD

**Issue by reinvanimschoot** [OpenWebslides/OpenWebslides#237] opened 2017-09-05 11:30 UTC

**Comment by reinvanimschoot** [comment] 2017-09-07 10:04
Waiting for @floriandejonckheere to set up the production server.

**Comment by floriandejonckheere** [comment] 2017-09-11 10:00
Duplicate of #222

**Closed by floriandejonckheere** 2017-09-11 10:00 UTC
Labels: feature
